parameters:
    characters:
        1:
            name: Finn
            name_ru: Фин Человек
            sex: male
        2:
            name: Jake
            name_ru: Джейк
            sex: male
        3:
            name: Princess Booblegum
            name_ru: Принцесса Бубльгум
            sex: female
        4:
            name: Ice King
            name_ru: Ледяной король
            sex: male
        5:
            name: Lady Raincorn
            name_ru: Леди ливнерог
            sex: female
        6:
            name: Marceline
            name_ru: Марселин
            sex: female
        7:
            name: Lumpy Space Princess
            name_ru: ППК
            sex: female
        8:
            name: BMO
            name_ru: БИМО
            sex: male
        9:
            name: Gunter
            name_ru: Гюнтер
            sex: male
        10:
            name: Earl Of Lemongrab
            name_ru: Лемон
            sex: male
        11:
            name: Flame Princess
            name_ru: Принцесса пламя
            sex: female

        12:
            name: Pappermit Butler
            name_ru: Конфета
            sex: male
        13:
            name: Lich
            name_ru: Лич
            sex: male
        14:
            name: Flambo
            name_ru: Флмабо
            sex: male
        15:
            name: Hunson Abadeer
            name_ru: Хансон Абадир
            sex: male
        16:
            name: Cinnamon Bun
            name_ru: ХЗ
            sex: male

        17:
            name: Party God
            name_ru: Бог вчероинок
            sex: male
        18:
            name: Ghost Princess
            name_ru: Принцесса призрак
            sex: female
        19:
            name: Party Pat
            name_ru: Мишка тусовщик
            sex: male

        20:
            name: Lollypop Girl
            name_ru: Деовчка леденец
            sex: female
        21:
            name: Prismo
            name_ru: Призмо
            sex: male
        22:
            name: Billy
            name_ru: Билли
            sex: male

        23:
            name: Cosmic Owl
            name_ru: Космческая сова
            sex: female
        24:
            name: Starchy
            name_ru: ХЗ
            sex: male