#security
login_check:
    path: /login-check

logout:
    path: /logout

login:
    path: /login
    defaults: { _controller: AdventureTimeBundle:Security:login }

registration:
    path: /registration
    defaults: { _controller: AdventureTimeBundle:Security:registration }

remember_pass:
    path: /remember-pass
    defaults: { _controller: AdventureTimeBundle:Security:rememberPass }

#redirect to default page
default:
    path: /
    defaults: { _controller: AdventureTimeBundle:Default:defaultPage }

#personages
personage:
    path: /personage/{id}
    defaults: { _controller: AdventureTimeBundle:Personage:personage, id:null }

personages:
    path: /personages
    defaults: { _controller: AdventureTimeBundle:Personage:personages }

#profile
profile:
    path: /profile
    defaults: { _controller: AdventureTimeBundle:Profile:profile }

#information about site
information:
    path: /information
    defaults: { _controller: AdventureTimeBundle:Information:information }

#test
test:
    path: /test
    defaults: { _controller: AdventureTimeBundle:Test:test }